norminette main.c
norminette arg_check.c
norminette arg_check1.c
norminette readdir.c
norminette new_node.c
norminette ft_lstadd_to_head.c
norminette print_lst.c
norminette sort_lst.c
norminette swap_fields.c
norminette printing.c
norminette more_printing.c
